export const TOGGLE_REGISTRATION_FORM = "TOGGLE_REGISTRATION_FORM";
export const TOGGLE_AUTHENTICATION_FORM = "TOGGLE_AUTHENTICATION_FORM";
export const UPDATE_USER = "UPDATE_USER";
export const LOGOUT = "LOGOUT";
